# Generated by Django 4.2.1 on 2023-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEV', 'Developer'), ('MGR', 'Manager')], default='DEV', max_length=3),
        ),
    ]
